[package]
name = "idevice_pair"
version = "1.1.0"
edition = "2024"
rust-version = "1.95"

[dependencies]
idevice = { version = "0.1.68", features = [
  "afc",
  "core_device_proxy",
  "house_arrest",
  "installation_proxy",
  "mdns",
  "pair",
  "remote_pairing",
  "rsd",
  "tcp",
  "tunnel_tcp_stack",
  "usbmuxd",
] }
eframe = "0.36.2"
rfd = "0.17"
tokio = { version = "1.53.2", features = ["rt-multi-thread", "net", "sync", "time"] }
futures-util = "0.3.34"
mdns-sd = "0.21"
uuid = { version = "1.27", features = ["v4"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[target.'cfg(target_os = "macos")'.dependencies]
eframe = { version = "0.36.2", features = ["glow"] }
pollster = "1.0"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
